name: blacktom
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: 0.15.3
  cloud_firestore: 0.13.4
  provider: ^4.0.4
  flutter_spinkit: ^4.1.2
  google_fonts: ^0.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:

    - assets/batman_logos/white.png
    - assets/batman_logos/white_bg.png
    - assets/batman_logos/yellow_bg.png
    - assets/wallpapers/bg1.jpg
    - assets/batmen/
