name: blacktom
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.2.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.4.0
  provider: ^6.1.4
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:

    - assets/batman_logos/white.png
    - assets/batman_logos/white_bg.png
    - assets/batman_logos/yellow_bg.png
    - assets/wallpapers/home.jpg
    - assets/batmen/
    - assets/wallpapers/
    - assets/dealers/
    - assets/casino_slides/
