import 'package:blacktom/shared/playing_card.dart';

List<PlayingCard> allCards = [
  PlayingCard(
    value: 2,
    number: '2',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 3,
    number: '3',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 4,
    number: '4',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 5,
    number: '5',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 6,
    number: '6',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 7,
    number: '7',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 8,
    number: '8',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 9,
    number: '9',
    suit: 'hearts',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: '10',
    suit: 'hearts',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'J',
    suit: 'hearts',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'Q',
    suit: 'hearts',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'K',
    suit: 'hearts',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 11,
    number: 'A',
    suit: 'hearts',
    isTen: false,
    isAce: true,
  ),
  // ===============
  PlayingCard(
    value: 2,
    number: '2',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 3,
    number: '3',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 4,
    number: '4',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 5,
    number: '5',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 6,
    number: '6',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 7,
    number: '7',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 8,
    number: '8',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 9,
    number: '9',
    suit: 'diamonds',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: '10',
    suit: 'diamonds',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'J',
    suit: 'diamonds',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'Q',
    suit: 'diamonds',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'K',
    suit: 'diamonds',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 11,
    number: 'A',
    suit: 'diamonds',
    isTen: false,
    isAce: true,
  ),
  // ================
  PlayingCard(
    value: 2,
    number: '2',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 3,
    number: '3',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 4,
    number: '4',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 5,
    number: '5',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 6,
    number: '6',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 7,
    number: '7',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 8,
    number: '8',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 9,
    number: '9',
    suit: 'clubs',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: '10',
    suit: 'clubs',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'J',
    suit: 'clubs',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'Q',
    suit: 'clubs',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'K',
    suit: 'clubs',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 11,
    number: 'A',
    suit: 'clubs',
    isTen: false,
    isAce: true,
  ),
  // ===============
  PlayingCard(
    value: 2,
    number: '2',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 3,
    number: '3',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 4,
    number: '4',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 5,
    number: '5',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 6,
    number: '6',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 7,
    number: '7',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 8,
    number: '8',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 9,
    number: '9',
    suit: 'spades',
    isTen: false,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: '10',
    suit: 'spades',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'J',
    suit: 'spades',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'Q',
    suit: 'spades',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 10,
    number: 'K',
    suit: 'spades',
    isTen: true,
    isAce: false,
  ),
  PlayingCard(
    value: 11,
    number: 'A',
    suit: 'spades',
    isTen: false,
    isAce: true,
  ),
];

List<PlayingCard> deck = allCards + allCards + allCards + allCards;
